In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:\Users\soume\data fsds\Attribute Dataset.xlsx")

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [16]:
pd.read_excel(r"C:\Users\soume\data fsds\Attribute Dataset.xlsx",sheet_name = 'sudh',header = None)

# By default it takes sheet1 if you want to put other sheet then you have to mention the sheet name respectively.

          0         1         2
0    hgdrfd     bggbg   fggbfc
1      ffdf      fffv       bbb
2     gbffd       mjj       sdc
3   fdfdbbb        bb    ccdccs
4       fbf   hmmbhhm      xccx
5     ffdbf    nvhnvn     cxxc
6      nfgn    mnhhnv       yhg
7     bfbfd      bbmh  ggfgffdz
8       bgg      ntgr    deddwd
9  bffbbfbf  fggfbbbf     wdwwq

In [4]:
pd.read_excel(r"C:\Users\soume\data fsds\Attribute Dataset.xlsx",sheet_name = 'sudh1')

    erihehi        egr    ggre
0   fhiouoi      grtgg     ggg
1       NaN        trg  tggtrg
2  ibhiufgh  iuyuifghu  gtrtgg
3       NaN        NaN      gg
4       NaN     bfgfgb     NaN

In [20]:
pd.read_excel(r"C:\Users\soume\data fsds\Attribute Dataset.xlsx",sheet_name = 'sudh1',header = None , names=["A" , "B" ,"C"])

          A          B       C
0   erihehi        egr    ggre
1   fhiouoi      grtgg     ggg
2       NaN        trg  tggtrg
3  ibhiufgh  iuyuifghu  gtrtgg
4       NaN        NaN      gg
5       NaN     bfgfgb     NaN

In [15]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [17]:
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [19]:
df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [21]:
 df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [22]:
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [23]:
df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [24]:
df.tail(4)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [28]:
pd.read_csv(r"C:\Users\soume\data fsds\haberman.csv")

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [30]:
pd.read_csv(r"C:\Users\soume\data fsds\haberman.csv" ,header = None,names = ["Age" , "Patients year of operations" , "Number of positive" , "Survival status"])

     Age  Patients year of operations  Number of positive  Survival status
0     30                           64                   1                1
1     30                           62                   3                1
2     30                           65                   0                1
3     31                           59                   2                1
4     31                           65                   4                1
..   ...                          ...                 ...              ...
301   75                           62                   1                1
302   76                           67                   0                1
303   77                           65                   3                1
304   78                           65                   1                2
305   83                           58                   2                2

[306 rows x 4 columns]

In [36]:
pd.read_csv(r"C:\Users\soume\data fsds\haberman1.csv",header = None ,sep = "@")
# sep= "@" is menas that all the "@" will be separate from the data.

      0   1  2  3
0    30  64  1  1
1    30  62  3  1
2    30  65  0  1
3    31  59  2  1
4    31  65  4  1
..   ..  .. .. ..
301  75  62  1  1
302  76  67  0  1
303  77  65  3  1
304  78  65  1  2
305  83  58  2  2

[306 rows x 4 columns]

In [37]:
pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
data_csv = pd.read_csv("https://raw.githubusercontent.com/stefanb/gurs-rpe/master/data/NA.csv")
data_csv

,ENOTA,NA_MID,NA_ID,NA_UIME,NA_DJ,OB_MID,POV_KM2,D_OD,DV_OD,STATUS,CEN_E,CEN_N
0,NaN,10083931,1,Ajdovščina,NaN,11026516,6.95,1995/01/01,1995/01/01,V,414738,83647
1,NaN,10083940,2,Batuje,NaN,11026516,2.83,1995/01/01,1995/01/01,V,405088,84487
2,NaN,10083958,3,Bela,NaN,11026516,4.90,1995/01/01,1995/01/01,V,424698,80817
3,NaN,10083966,4,Brje,NaN,11026516,5.35,1995/01/01,1995/01/01,V,408018,81637
4,NaN,10083974,5,Budanje,NaN,11026516,5.33,1995/01/01,1995/01/01,V,418629,82078
...,...,...,...,...,...,...,...,...,...,...,...,...
6031,NaN,24031837,22,Draga,NaN,11026907,1.91,2007/05/29,2007/05/29,V,464809,89826
6032,NaN,24032698,23,Podgozd,NaN,11026907,1.02,2007/06/14,2007/06/14,V,464139,88006
6033,NaN,24034160,24,Podkraj,NaN,11026907,2.46,2007/08/06,2007/08/06,V,457269,92796
6034,NaN,24034313,25,Suša,NaN,11026907,1.01,2007/07/26,2007/08/13,V,465849,85616
6035,NaN,24267245,14,Šestdobe,NaN,11027245,1.12,2013/05/09,2013/05/10,V,546186,148728

In [5]:
data_csv.columns

Index(['ENOTA', 'NA_MID', 'NA_ID', 'NA_UIME', 'NA_DJ', 'OB_MID', 'POV_KM2',
       'D_OD', 'DV_OD', 'STATUS', 'CEN_E', 'CEN_N'],
      dtype='object')

In [39]:
a = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")
a

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [40]:
type(a)

list

In [43]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [6]:
js = pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")
js

#Reading json (Java Script Object Notation) format: Combination of Dictionaries: We can use json viewer online to understand json in better way
#Keys become our column and Row becomes our values of those keys

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47929,1325322319,PR_kwDOAA0YD848ekkq,47929,TST: Allow “no setter” messages from Python 3.11,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Loosen “`can't set attribute`” expected messag...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47928,1325302562,I_kwDOAA0YD85O_oMi,47928,"Potential issue when running ""python ./scripts...",...,NaT,NONE,NaN,NaN,NaN,When a user runs the command `python ./scripts...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47927,1325295091,PR_kwDOAA0YD848ee1r,47927,ENH: Support For Interval __contains__ Other I...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46613\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47926,1325249220,PR_kwDOAA0YD848eVEC,47926,TYP: pandas.core.series annotations from panda...,...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47925,1325180386,PR_kwDOAA0YD848eG5j,47925,Backport PR #47905: BUG: Fix read_xml raising ...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Manual Backport #47905 \r\n\r\n- [X] [Tests ad...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47924,1325050466,PR_kwDOAA0YD848dre2,47924,DOC: Move whatsnew for indexing regression,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Moves the whatsnew\r\n,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47922,1325033398,PR_kwDOAA0YD848dnpH,47922,DOC: Add pandas-stubs and potential 2.0 API br...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47921,1325007344,PR_kwDOAA0YD848dh-F,47921,Backport PR #45287 on branch 1.4.x (BUG: frame...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,\r\nLets see if this works,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47919,1324959124,I_kwDOAA0YD85O-UWU,47919,"WARN,TST check stacklevel for all warnings",...,NaT,MEMBER,NaN,NaN,NaN,"Currently, the stacklevel is only checked for ...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47918,1324939192,PR_kwDOAA0YD848dTlI,47918,ERR: Raise TypeError when Series.str.get passe...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #47911 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47917,1324938330,I_kwDOAA0YD85O-PRa,47917,BUG: groupby.shift not respecting as_index,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47914,1324424482,I_kwDOAA0YD85O8R0i,47914,ENH: moving columns to first or last index of ...,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47913,1323933956,PR_kwDOAA0YD848Z8xf,47913,⬆️ UPGRADE: Autoupdate pre-commit config,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,<!-- START pr-commits -->\n<!-- END pr-commits...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47911,1323658424,I_kwDOAA0YD85O5Wy4,47911,DOC/TST: pandas.Series.str.get with dict eleme...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47910,1323494729,I_kwDOAA0YD85O4u1J,47910,ENH: Allowing more control over the asserion p...,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47909,1323470827,PR_kwDOAA0YD848Yasj,47909,REF move find_stack_level to _libs,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,"Precursor to #47908 , moving `find_stack_level...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47908,1323448835,PR_kwDOAA0YD848YWfB,47908,Fix stacklevel dayfirst warning,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #47907 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47907,1323445152,I_kwDOAA0YD85O4iug,47907,BUG: stacklevel from dayfirst warning incorrect,...,NaT,MEMBER,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47901,1322663615,PR_kwDOAA0YD848Vwyp,47901,ENH: Move warnings to error/__init__.py per GH...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] xref #27656. this GitHub issue is being ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47899,1322445397,I_kwDOAA0YD85O0upV,47899,BUG: read_html produce UnicodeEncodeError for ...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47895,1322204353,I_kwDOAA0YD85OzzzB,47895,BUG in read_pickle,...,NaT,NONE,NaN,NaN,NaN,Summary: read_pickle from Pandas version > 1.2...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47887,1321467204,PR_kwDOAA0YD848Rx2r,47887,REF: Change _NULL_DESCRIPTION[datetime] to use...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47886,1321439947,PR_kwDOAA0YD848RrrQ,47886,REF: PandasColumn.describe_categorical returns...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47884,1321128491,I_kwDOAA0YD85OvtIr,47884,Pandas string dtype needs from NumPy - prototy...,...,NaT,NONE,NaN,NaN,NaN,The purpose of this issue is to discuss a plan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47883,1320820720,I_kwDOAA0YD85Ouh_w,47883,BUG: Unexpected results when adding offsets to...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47882,1320788915,I_kwDOAA0YD85OuaOz,47882,BUG: FutureWarning for timezone-naive date tim...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47879,1319991298,I_kwDOAA0YD85OrXgC,47879,PERF: preserve Index._id through pickle round-...,...,NaT,MEMBER,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47874,1319462792,I_kwDOAA0YD85OpWeI,47874,BUG: `to_sql` string to date and/or time conve...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47872,1319315302,I_kwDOAA0YD85Ooydm,47872,ENH: Allow different `dtype` in `pandas.Series...,...,NaT,NONE,NaN,NaN,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47871,1318922970,I_kwDOAA0YD85OnSra,47871,BUG: to_csv requires escapechar unnecessarily ...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [7]:
js.head(2)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/47929,1325322319,PR_kwDOAA0YD848ekkq,47929,TST: Allow “no setter” messages from Python 3.11,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Loosen “`can't set attribute`” expected messag...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/47928,1325302562,I_kwDOAA0YD85O_oMi,47928,"Potential issue when running ""python ./scripts...",...,NaT,NONE,NaN,NaN,NaN,When a user runs the command `python ./scripts...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [50]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app', 'state_reason'],
      dtype='object')

In [52]:
js["repository_url"]

0     https://api.github.com/repos/pandas-dev/pandas
1     https://api.github.com/repos/pandas-dev/pandas
2     https://api.github.com/repos/pandas-dev/pandas
3     https://api.github.com/repos/pandas-dev/pandas
4     https://api.github.com/repos/pandas-dev/pandas
5     https://api.github.com/repos/pandas-dev/pandas
6     https://api.github.com/repos/pandas-dev/pandas
7     https://api.github.com/repos/pandas-dev/pandas
8     https://api.github.com/repos/pandas-dev/pandas
9     https://api.github.com/repos/pandas-dev/pandas
10    https://api.github.com/repos/pandas-dev/pandas
11    https://api.github.com/repos/pandas-dev/pandas
12    https://api.github.com/repos/pandas-dev/pandas
13    https://api.github.com/repos/pandas-dev/pandas
14    https://api.github.com/repos/pandas-dev/pandas
15    https://api.github.com/repos/pandas-dev/pandas
16    https://api.github.com/repos/pandas-dev/pandas
17    https://api.github.com/repos/pandas-dev/pandas
18    https://api.github.com/repos/pandas-dev/pandas
19    https://api.github.com/repos/pandas-dev/pandas
20    https://api.github.com/repos/pandas-dev/pandas
21    https://api.github.com/repos/pandas-dev/pandas
22    https://api.github.com/repos/pandas-dev/pandas
23    https://api.github.com/repos/pandas-dev/pandas
24    https://api.github.com/repos/pandas-dev/pandas
25    https://api.github.com/repos/pandas-dev/pandas
26    https://api.github.com/repos/pandas-dev/pandas
27    https://api.github.com/repos/pandas-dev/pandas
28    https://api.github.com/repos/pandas-dev/pandas
29    https://api.github.com/repos/pandas-dev/pandas
Name: repository_url, dtype: object

In [53]:
js["user"]

0     {'login': 'skrawcz', 'id': 2328071, 'node_id':...
1     {'login': 'attack68', 'id': 24256554, 'node_id...
2     {'login': 'Dr-Irv', 'id': 15113894, 'node_id':...
3     {'login': 'Codeberg-AsGithubAlternative-buhtz'...
4     {'login': 'dannyi96', 'id': 15380498, 'node_id...
5     {'login': 'weikhor', 'id': 36619387, 'node_id'...
6     {'login': 'seanslma', 'id': 30691708, 'node_id...
7     {'login': 'mroeschke', 'id': 10647082, 'node_i...
8     {'login': 'mroeschke', 'id': 10647082, 'node_i...
9     {'login': 'PriestlyAdejo', 'id': 108146732, 'n...
10    {'login': 'rhshadrach', 'id': 45562402, 'node_...
11    {'login': 'twoertwein', 'id': 6618166, 'node_i...
12    {'login': 'dannyi96', 'id': 15380498, 'node_id...
13    {'login': 'bherwerth', 'id': 108834862, 'node_...
14    {'login': 'StefRe', 'id': 19879328, 'node_id':...
15    {'login': 'windowshopr', 'id': 40477419, 'node...
16    {'login': 'bzhaoopenstack', 'id': 11386522, 'n...
17    {'login': 'PriestlyAdejo', 'id': 108146732, 'n...
18    {'login': 'GivyBoy', 'id': 58392771, 'node_id'...
19    {'login': 'mattB1989', 'id': 13086632, 'node_i...
20    {'login': 'bherwerth', 'id': 108834862, 'node_...
21    {'login': 'ravindrabajpai', 'id': 1445512, 'no...
22    {'login': 'rhshadrach', 'id': 45562402, 'node_...
23    {'login': 'jbrockmendel', 'id': 8078968, 'node...
24    {'login': 'shourya5', 'id': 73142986, 'node_id...
25    {'login': 'adrienpacifico', 'id': 6614121, 'no...
26    {'login': 'attack68', 'id': 24256554, 'node_id...
27    {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
28    {'login': 'MarcoGorelli', 'id': 33491632, 'nod...
29    {'login': 'GivyBoy', 'id': 58392771, 'node_id'...
Name: user, dtype: object

In [54]:
js["user"][0]

{'login': 'skrawcz',
 'id': 2328071,
 'node_id': 'MDQ6VXNlcjIzMjgwNzE=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/2328071?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/skrawcz',
 'html_url': 'https://github.com/skrawcz',
 'followers_url': 'https://api.github.com/users/skrawcz/followers',
 'following_url': 'https://api.github.com/users/skrawcz/following{/other_user}',
 'gists_url': 'https://api.github.com/users/skrawcz/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/skrawcz/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/skrawcz/subscriptions',
 'organizations_url': 'https://api.github.com/users/skrawcz/orgs',
 'repos_url': 'https://api.github.com/users/skrawcz/repos',
 'events_url': 'https://api.github.com/users/skrawcz/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/skrawcz/received_events',
 'type': 'User',
 'site_admin': False}

In [55]:
df = pd.read_excel(r"C:\Users\soume\data fsds\Attribute Dataset.xlsx")

In [56]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [57]:
df.to_json("json_transfer.json")
# Converting data to json

In [58]:
pwd

'C:\\Users\\soume\\My class work@iNeuron'

In [ ]:
#pwd #Present Working Directory
#Spark Dataframe is faster than Pandas Dataframe because it uses optimizer internally.

In [59]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [63]:
df.to_csv("D://test22112.csv",index= False)

In [1]:
pwd

'C:\\Users\\soume\\My class work@iNeuron'